apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dice-roller
  description: It rolls dice
  tags:
    - go
  annotations:
    backstage.io/kubernetes-id: dice-roller
    backstage.io/techdocs-ref: dice-roller
    # 'backstage.io/kubernetes-namespace': enbl
    # backstage.io/kubernetes-label-selector: 'backstage.io/kubernetes-id=dice-roller'
spec:
  type: service
  lifecycle: production
  owner: delivery
